stages:
  - test

run-android-python-tests-on-mac:
  stage: test
  rules:
    - when: always
  tags:
    - android
    - mac
  script:
    - sh run-tests-mac.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - AltUnityTesterLog.txt
